import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from './../styles/Home.module.scss'
import { CardFront, ICardFront } from '../components/cardFront'
import { CardBack } from '../components/cardBack'
import { Form } from '../components/Form'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.containerLeft}>
          <div className={styles.teste}>
            <CardFront></CardFront>
            <CardBack></CardBack>
          </div>
        </div>
        <div className={styles.containerRight}>
          <Form></Form>
        </div>

      </main>
    </>
  )
}
